import { createHash } from 'node:crypto';
import type { DatabaseSync } from 'node:sqlite';
import type { SqliteDatabase } from './database.js';

export interface DriftSnapshotRecord {
  readonly id: string; readonly ownerKey: string; readonly kind: 'capture' | 'comparison';
  readonly requestFingerprint: string; readonly runToken: string;
  readonly state: 'collecting' | 'complete' | 'partial' | 'unavailable' | 'interrupted';
  readonly header: unknown; readonly createdAt: number; readonly expiresAt: number; readonly updatedAt: number;
  readonly snapshotHash: string | null; readonly approvedAt: number | null;
}
export interface DriftEvidenceRecord { readonly snapshotId: string; readonly sequence: number; readonly hash: string; readonly payload: unknown; }
interface SnapshotRow { owner_key: unknown; id: unknown; kind: unknown; request_fingerprint: unknown; run_token: unknown; state: unknown; header_json: unknown; created_at: unknown; expires_at: unknown; updated_at: unknown; snapshot_hash: unknown; approved_at: unknown; approval_hash: unknown; }
interface DecodedSnapshot extends DriftSnapshotRecord { readonly approvalHash: string | null; }
interface EvidenceRow { owner_key: unknown; snapshot_id: unknown; sequence: unknown; hash: unknown; payload_json: unknown; }
const OWNER=/^[a-f0-9]{64}$/, HASH=/^[a-f0-9]{64}$/, ID=/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/;
const STATES=new Set(['collecting','complete','partial','unavailable','interrupted']), TERMINAL=new Set(['complete','partial','unavailable','interrupted']);
const HEADER_MAX=32*1024, ROW_MAX=20, BYTES_MAX=64*1024, PAYLOAD_MAX=4096;
const SNAPSHOT_COLS=`CASE WHEN typeof(owner_key)='text' AND length(CAST(owner_key AS BLOB))<=64 THEN owner_key END owner_key,CASE WHEN typeof(id)='text' AND length(CAST(id AS BLOB))<=128 THEN id END id,CASE WHEN typeof(kind)='text' AND length(CAST(kind AS BLOB))<=16 THEN kind END kind,CASE WHEN typeof(request_fingerprint)='text' AND length(CAST(request_fingerprint AS BLOB))<=64 THEN request_fingerprint END request_fingerprint,CASE WHEN typeof(run_token)='text' AND length(CAST(run_token AS BLOB))<=64 THEN run_token END run_token,CASE WHEN typeof(state)='text' AND length(CAST(state AS BLOB))<=16 THEN state END state,CASE WHEN typeof(header_json)='text' AND length(CAST(header_json AS BLOB))<=${HEADER_MAX} THEN header_json END header_json,CASE WHEN typeof(created_at)='integer' AND created_at BETWEEN 0 AND ${Number.MAX_SAFE_INTEGER} THEN created_at END created_at,CASE WHEN typeof(expires_at)='integer' AND expires_at BETWEEN 0 AND ${Number.MAX_SAFE_INTEGER} THEN expires_at END expires_at,CASE WHEN typeof(updated_at)='integer' AND updated_at BETWEEN 0 AND ${Number.MAX_SAFE_INTEGER} THEN updated_at END updated_at,CASE WHEN snapshot_hash IS NULL THEN NULL WHEN typeof(snapshot_hash)='text' AND length(CAST(snapshot_hash AS BLOB))<=64 THEN snapshot_hash ELSE 'INVALID' END snapshot_hash,CASE WHEN approved_at IS NULL THEN NULL WHEN typeof(approved_at)='integer' AND approved_at BETWEEN 0 AND ${Number.MAX_SAFE_INTEGER} THEN approved_at ELSE -1 END approved_at,CASE WHEN approval_hash IS NULL THEN NULL WHEN typeof(approval_hash)='text' AND length(CAST(approval_hash AS BLOB))<=64 THEN approval_hash ELSE 'INVALID' END approval_hash`;
const EVIDENCE_COLS=`CASE WHEN typeof(owner_key)='text' AND length(CAST(owner_key AS BLOB))<=64 THEN owner_key END owner_key,CASE WHEN typeof(snapshot_id)='text' AND length(CAST(snapshot_id AS BLOB))<=128 THEN snapshot_id END snapshot_id,CASE WHEN typeof(sequence)='integer' AND sequence BETWEEN 1 AND ${Number.MAX_SAFE_INTEGER} THEN sequence END sequence,CASE WHEN typeof(hash)='text' AND length(CAST(hash AS BLOB))<=64 THEN hash END hash,CASE WHEN typeof(payload_json)='text' AND length(CAST(payload_json AS BLOB))<=${PAYLOAD_MAX} THEN payload_json END payload_json`;

export class SqliteDriftRepository {
  public constructor(private readonly database:SqliteDatabase){}
  public get(owner:string,id:string):DriftSnapshotRecord|null {
    if(!validOwner(owner)||!validId(id))return null;
    const raw=this.database.connection.prepare(`SELECT ${SNAPSHOT_COLS} FROM drift_snapshots WHERE owner_key=? AND id=?`).get(owner,id) as SnapshotRow|undefined;
    if(!raw)return null; const record=decodeSnapshot(raw);
    if(record.state!=='collecting') this.validateTerminal(record);
    return publicSnapshot(record);
  }
  public create(r:DriftSnapshotRecord):boolean {
    const json=canonicalJson(r.header);
    if(!validOwner(r.ownerKey)||!validId(r.id)||!validHash(r.requestFingerprint)||!validHash(r.runToken)||!['capture','comparison'].includes(r.kind)||r.state!=='collecting'||r.snapshotHash!==null||r.approvedAt!==null||!isObject(r.header)||json===null||bytes(json)>HEADER_MAX||!validTime(r.createdAt)||!validTime(r.expiresAt)||!validTime(r.updatedAt)||r.expiresAt<r.createdAt||r.updatedAt<r.createdAt)return false;
    return this.tx(db=>{if(db.prepare('SELECT 1 FROM drift_snapshots WHERE owner_key=? AND id=?').get(r.ownerKey,r.id))return false;const own=db.prepare('SELECT COUNT(*) n FROM drift_snapshots WHERE owner_key=?').get(r.ownerKey) as {n:number|bigint};const all=db.prepare('SELECT COUNT(*) n FROM drift_snapshots').get() as {n:number|bigint};if(Number(own.n)>=32||Number(all.n)>=256)return false;db.prepare('INSERT INTO drift_snapshots(owner_key,id,kind,request_fingerprint,run_token,state,header_json,created_at,expires_at,updated_at,snapshot_hash,approved_at,approval_hash) VALUES(?,?,?,?,?,?,?,?,?,?,NULL,NULL,NULL)').run(r.ownerKey,r.id,r.kind,r.requestFingerprint,r.runToken,'collecting',json,r.createdAt,r.expiresAt,r.updatedAt);return true;});
  }
  public append(owner:string,id:string,token:string,payload:unknown,now:number):DriftEvidenceRecord|null {
    const json=canonicalJson(payload);if(!validOwner(owner)||!validId(id)||!validHash(token)||!validTime(now)||json===null||bytes(json)>PAYLOAD_MAX)return null;
    return this.tx(db=>{const r=this.readSnapshot(db,owner,id);if(!r||r.state!=='collecting'||r.runToken!==token||now<r.createdAt||now<r.updatedAt||now>r.expiresAt)return null;const rows=this.readAllEvidence(owner,id);const used=rows.reduce((n,x)=>n+bytes(canonicalJson(x.payload)!),0);if(rows.length>=ROW_MAX||used+bytes(json)>BYTES_MAX)return null;const sequence=rows.length+1,hash=sha(json);db.prepare('INSERT INTO drift_evidence(owner_key,snapshot_id,sequence,hash,payload_json) VALUES(?,?,?,?,?)').run(owner,id,sequence,hash,json);return {snapshotId:id,sequence,hash,payload};});
  }
  public listEvidence(owner:string,id:string,after=0,limit=20):DriftEvidenceRecord[]{if(!validOwner(owner)||!validId(id)||!Number.isSafeInteger(after)||after<0||!Number.isInteger(limit)||limit<1||limit>20)return[];const snapshot=this.get(owner,id);if(!snapshot)return[];return this.readAllEvidence(owner,id).filter(x=>x.sequence>after).slice(0,limit);}
  public summary(owner:string,id:string):{count:number;bytes:number}|null{const r=this.get(owner,id);if(!r)return null;const rows=this.readAllEvidence(owner,id),size=rows.reduce((n,x)=>n+bytes(canonicalJson(x.payload)!),0);return{count:rows.length,bytes:size};}
  public finish(owner:string,id:string,token:string,state:'complete'|'partial'|'unavailable'|'interrupted',now:number):DriftSnapshotRecord|null {
    if(!validOwner(owner)||!validId(id)||!validHash(token)||!TERMINAL.has(state)||!validTime(now))return null;
    return this.tx(db=>{const r=this.readSnapshot(db,owner,id);if(!r||r.runToken!==token||r.state!=='collecting'||now<r.createdAt||now<r.updatedAt||now>r.expiresAt)return null;const rows=this.readAllEvidence(owner,id);const hash=snapshotHash(r,state,rows);const changed=db.prepare("UPDATE drift_snapshots SET state=?,updated_at=?,snapshot_hash=? WHERE owner_key=? AND id=? AND run_token=? AND state='collecting'").run(state,now,hash,owner,id,token);return Number(changed.changes)===1?publicSnapshot({...r,state,updatedAt:now,snapshotHash:hash}):null;});
  }
  public approve(owner:string,id:string,exactHash:string,now:number):DriftSnapshotRecord|null {
    if(!validOwner(owner)||!validId(id)||!validHash(exactHash)||!validTime(now))return null;
    return this.tx(db=>{const r=this.readSnapshot(db,owner,id);if(!r)return null;this.validateTerminal(r);if(r.approvedAt!==null)return r.snapshotHash===exactHash&&r.kind==='capture'&&r.state==='complete'?publicSnapshot(r):null;if(r.kind!=='capture'||r.state!=='complete'||r.snapshotHash!==exactHash||now<r.createdAt||now<r.updatedAt)return null;const proof=approvalHash(owner,id,exactHash,now);const changed=db.prepare("UPDATE drift_snapshots SET approved_at=?,approval_hash=? WHERE owner_key=? AND id=? AND state='complete' AND kind='capture' AND snapshot_hash=? AND approved_at IS NULL AND approval_hash IS NULL").run(now,proof,owner,id,exactHash);return Number(changed.changes)===1?publicSnapshot({...r,approvedAt:now,approvalHash:proof}):null;});
  }
  private validateTerminal(r:DecodedSnapshot):void{const rows=this.readAllEvidence(r.ownerKey,r.id);if(r.state==='collecting'){if(r.snapshotHash!==null||r.approvedAt!==null||r.approvalHash!==null)throw corrupt();return;}if(!validHash(r.snapshotHash)||snapshotHash(r,r.state,rows)!==r.snapshotHash)throw corrupt();if(r.approvedAt===null){if(r.approvalHash!==null)throw corrupt();return;}if(r.kind!=='capture'||r.state!=='complete'||r.approvedAt<r.createdAt||r.approvedAt<r.updatedAt||!validHash(r.approvalHash)||approvalHash(r.ownerKey,r.id,r.snapshotHash,r.approvedAt)!==r.approvalHash)throw corrupt();}
  private readSnapshot(db:DatabaseSync,owner:string,id:string):DecodedSnapshot|null{const raw=db.prepare(`SELECT ${SNAPSHOT_COLS} FROM drift_snapshots WHERE owner_key=? AND id=?`).get(owner,id) as SnapshotRow|undefined;return raw?decodeSnapshot(raw):null;}
  private readAllEvidence(owner:string,id:string):DriftEvidenceRecord[]{const rows=this.database.connection.prepare(`SELECT ${EVIDENCE_COLS} FROM drift_evidence WHERE owner_key=? AND snapshot_id=? ORDER BY sequence LIMIT 21`).all(owner,id) as unknown as EvidenceRow[];if(rows.length>ROW_MAX)throw corrupt();const decoded=rows.map(x=>decodeEvidence(x,owner,id));const size=decoded.reduce((n,x)=>n+bytes(canonicalJson(x.payload)!),0);if(decoded.some((x,i)=>x.sequence!==i+1)||size>BYTES_MAX)throw corrupt();return decoded;}
  private tx<T>(f:(db:DatabaseSync)=>T):T{const db=this.database.connection;db.exec('BEGIN IMMEDIATE');try{const value=f(db);db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}}
}
function decodeSnapshot(x:SnapshotRow):DecodedSnapshot{if(typeof x.header_json!=='string'||bytes(x.header_json)>HEADER_MAX)throw corrupt();let header:unknown;try{header=JSON.parse(x.header_json) as unknown;}catch{throw corrupt();}if(!validOwner(x.owner_key)||!validId(x.id)||!['capture','comparison'].includes(String(x.kind))||!validHash(x.request_fingerprint)||!validHash(x.run_token)||!STATES.has(String(x.state))||!isObject(header)||canonicalJson(header)!==x.header_json||!validTime(x.created_at)||!validTime(x.expires_at)||!validTime(x.updated_at)||Number(x.expires_at)<Number(x.created_at)||Number(x.updated_at)<Number(x.created_at)||!(x.snapshot_hash===null||validHash(x.snapshot_hash))||!(x.approved_at===null||validTime(x.approved_at))||!(x.approval_hash===null||validHash(x.approval_hash)))throw corrupt();const state=x.state as DriftSnapshotRecord['state'],snapshot=x.snapshot_hash as string|null,approvedAt=x.approved_at===null?null:Number(x.approved_at),approval=x.approval_hash as string|null;if(state==='collecting'&&(snapshot!==null||approvedAt!==null||approval!==null))throw corrupt();if(state!=='collecting'&&approvedAt===null&&approval!==null)throw corrupt();return{id:x.id,ownerKey:x.owner_key,kind:x.kind as DriftSnapshotRecord['kind'],requestFingerprint:x.request_fingerprint,runToken:x.run_token,state,header,createdAt:Number(x.created_at),expiresAt:Number(x.expires_at),updatedAt:Number(x.updated_at),snapshotHash:snapshot,approvedAt,approvalHash:approval};}
function decodeEvidence(x:EvidenceRow,owner:string,id:string):DriftEvidenceRecord{if(x.owner_key!==owner||x.snapshot_id!==id||!validId(x.snapshot_id)||!validTime(x.sequence)||Number(x.sequence)<1||!validHash(x.hash)||typeof x.payload_json!=='string'||bytes(x.payload_json)>PAYLOAD_MAX)throw corrupt();let payload:unknown;try{payload=JSON.parse(x.payload_json) as unknown;}catch{throw corrupt();}if(canonicalJson(payload)!==x.payload_json||sha(x.payload_json)!==x.hash)throw corrupt();return{snapshotId:x.snapshot_id,sequence:Number(x.sequence),hash:x.hash,payload};}
function snapshotHash(r:DriftSnapshotRecord,state:DriftSnapshotRecord['state'],rows:DriftEvidenceRecord[]):string{const json=canonicalJson({id:r.id,ownerKey:r.ownerKey,kind:r.kind,requestFingerprint:r.requestFingerprint,header:r.header,createdAt:r.createdAt,expiresAt:r.expiresAt,state,rows:rows.map(x=>({sequence:x.sequence,hash:x.hash}))});if(json===null)throw corrupt();return sha(json);}
function approvalHash(owner:string,id:string,snapshotHashValue:string,approvedAt:number):string{const json=canonicalJson({ownerKey:owner,id,snapshotHash:snapshotHashValue,approvedAt});if(json===null)throw corrupt();return sha(json);}
function publicSnapshot(r:DecodedSnapshot):DriftSnapshotRecord{return{id:r.id,ownerKey:r.ownerKey,kind:r.kind,requestFingerprint:r.requestFingerprint,runToken:r.runToken,state:r.state,header:r.header,createdAt:r.createdAt,expiresAt:r.expiresAt,updatedAt:r.updatedAt,snapshotHash:r.snapshotHash,approvedAt:r.approvedAt};}
function canonicalJson(v:unknown):string|null{try{const json=JSON.stringify(sort(v,0,new Set()));return typeof json==='string'?json:null;}catch{return null;}}
function sort(v:unknown,d:number,a:Set<object>):unknown{if(d>32)throw Error();if(v===null||typeof v==='string'||typeof v==='boolean')return v;if(typeof v==='number'){if(!Number.isFinite(v))throw Error();return v;}if(typeof v!=='object')throw Error();if(a.has(v))throw Error();a.add(v);try{if(Array.isArray(v)){if(Object.getPrototypeOf(v)!==Array.prototype||Object.getOwnPropertySymbols(v).length||Object.keys(v).length!==v.length)throw Error();return Array.from({length:v.length},(_,i)=>sort(v[i],d+1,a));}const p=Object.getPrototypeOf(v);if(p!==Object.prototype&&p!==null||Reflect.ownKeys(v).length!==Object.keys(v).length)throw Error();const out=Object.create(null) as Record<string,unknown>;for(const k of Object.keys(v).sort()){const desc=Object.getOwnPropertyDescriptor(v,k);if(!desc||!('value'in desc))throw Error();out[k]=sort(desc.value,d+1,a);}return out;}finally{a.delete(v);}}
function isObject(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}function bytes(s:string):number{return Buffer.byteLength(s,'utf8');}function sha(s:string):string{return createHash('sha256').update(s,'utf8').digest('hex');}function validId(v:unknown):v is string{return typeof v==='string'&&ID.test(v);}function validOwner(v:unknown):v is string{return typeof v==='string'&&OWNER.test(v);}function validHash(v:unknown):v is string{return typeof v==='string'&&HASH.test(v);}function validTime(v:unknown):v is number{return typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;}function corrupt():Error{return new Error('Drift data is corrupt');}
