import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { SqliteDatabase } from './database.js';
import { SqliteDriftRepository, type DriftSnapshotRecord } from './drift-repository.js';

const roots:string[]=[], dbs:SqliteDatabase[]=[];
afterEach(async()=>{for(const db of dbs.splice(0)){try{db.close();}catch{/* closed by reopen case */}}await Promise.all(roots.splice(0).map(r=>rm(r,{recursive:true,force:true})));});
async function setup():Promise<{file:string;db:SqliteDatabase;repo:SqliteDriftRepository}>{const root=await mkdtemp(path.join(os.tmpdir(),'drift-'));roots.push(root);const file=path.join(root,'db.sqlite'),db=new SqliteDatabase(file);dbs.push(db);return{file,db,repo:new SqliteDriftRepository(db)};}
const owner='a'.repeat(64), other='b'.repeat(64), request='c'.repeat(64), token='d'.repeat(64), now=1_800_000_000_000;
function record(id='capture-1',ownerKey=owner):DriftSnapshotRecord{return{id,ownerKey,kind:'capture',requestFingerprint:request,runToken:token,state:'collecting',header:{targets:['health']},createdAt:now,expiresAt:now+60_000,updatedAt:now,snapshotHash:null,approvedAt:null};}

describe('SqliteDriftRepository',()=>{
  it('persists immutable snapshots and evidence across reopen with owner isolation',async()=>{const{file,db,repo}=await setup();const r=record();expect(repo.create(r)).toBe(true);expect(repo.get(other,r.id)).toBeNull();expect(repo.append(owner,r.id,token,{z:1,a:2},now)?.sequence).toBe(1);const done=repo.finish(owner,r.id,token,'complete',now+1);expect(done?.snapshotHash).toMatch(/^[a-f0-9]{64}$/);expect(repo.get(owner,r.id)).toEqual(done);expect(repo.append(owner,r.id,token,{late:true},now+2)).toBeNull();db.close();const reopened=new SqliteDatabase(file);dbs.push(reopened);const again=new SqliteDriftRepository(reopened);expect(again.get(owner,r.id)).toEqual(done);expect(again.listEvidence(owner,r.id)).toHaveLength(1);});
  it('serializes competing connections and fences stale, expired and reversed writes',async()=>{const{file,repo}=await setup();repo.create(record());const peerDb=new SqliteDatabase(file);dbs.push(peerDb);const peer=new SqliteDriftRepository(peerDb);expect(repo.append(owner,'capture-1',token,{ok:1},now)).not.toBeNull();expect(peer.append(owner,'capture-1',token,{ok:2},now)).not.toBeNull();expect(repo.finish(owner,'capture-1',token,'complete',now-1)).toBeNull();expect(peer.finish(owner,'capture-1',token,'complete',now+60_001)).toBeNull();expect(repo.finish(owner,'capture-1',token,'complete',now+1)).not.toBeNull();expect(peer.finish(owner,'capture-1',token,'partial',now+2)).toBeNull();expect(peer.append(owner,'capture-1',token,{late:1},now+2)).toBeNull();});
  it('approves only an exact complete capture hash and never refreshes approval time',async()=>{const{repo}=await setup();repo.create(record());const done=repo.finish(owner,'capture-1',token,'complete',now+1)!;expect(repo.approve(owner,'capture-1','e'.repeat(64),now+2)).toBeNull();const approved=repo.approve(owner,'capture-1',done.snapshotHash!,now+2)!;expect(approved.approvedAt).toBe(now+2);expect(repo.approve(owner,'capture-1',done.snapshotHash!,now+9)).toEqual(approved);expect(repo.approve(owner,'capture-1','e'.repeat(64),now+9)).toBeNull();});
  it('enforces row, header and evidence byte bounds and rejects non-JSON canaries',async()=>{const{repo}=await setup();expect(repo.create({...record(),header:{s:'x'.repeat(32*1024)}})).toBe(false);expect(repo.create({...record(),id:'bad id'})).toBe(false);expect(repo.create(record())).toBe(true);expect(repo.append(owner,'capture-1',token,{secret:undefined},now)).toBeNull();expect(repo.append(owner,'capture-1',token,{secret:1n},now)).toBeNull();for(let i=0;i<20;i++)expect(repo.append(owner,'capture-1',token,{n:i},now)).not.toBeNull();expect(repo.append(owner,'capture-1',token,{extra:1},now)).toBeNull();expect(repo.summary(owner,'capture-1')?.count).toBe(20);});
  it('enforces the aggregate evidence byte quota',async()=>{const{repo}=await setup();repo.create(record());const value={s:'x'.repeat(4000)};for(let i=0;i<16;i++)expect(repo.append(owner,'capture-1',token,value,now)).not.toBeNull();expect(repo.append(owner,'capture-1',token,value,now)).toBeNull();expect(repo.summary(owner,'capture-1')).toEqual({count:16,bytes:16*4008});});
  it('rejects tampered projections and detects deleted terminal evidence',async()=>{const{db,repo}=await setup();repo.create(record());repo.append(owner,'capture-1',token,{safe:true},now);const done=repo.finish(owner,'capture-1',token,'complete',now+1)!;db.connection.prepare('DELETE FROM drift_evidence WHERE owner_key=? AND snapshot_id=?').run(owner,'capture-1');expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');expect(()=>repo.approve(owner,'capture-1',done.snapshotHash!,now+2)).toThrow('Drift data is corrupt');});
  it('fails closed on malformed SQL-stored fields before JavaScript materialization',async()=>{const{db,repo}=await setup();repo.create(record());db.connection.prepare('UPDATE drift_snapshots SET header_json=? WHERE owner_key=?').run('x'.repeat(40*1024),owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');});
  it('rejects non-null hash or approval fields on collecting snapshots',async()=>{const{db,repo}=await setup();repo.create(record());
    db.connection.prepare('UPDATE drift_snapshots SET snapshot_hash=? WHERE owner_key=?').run('a'.repeat(65),owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');
    db.connection.prepare('UPDATE drift_snapshots SET snapshot_hash=NULL,approved_at=? WHERE owner_key=?').run(now,owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');
    db.connection.prepare('UPDATE drift_snapshots SET approved_at=NULL,approval_hash=? WHERE owner_key=?').run('a'.repeat(64),owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');
  });
  it('binds approval timestamp and digest and rejects malformed stored approval columns',async()=>{const{db,repo}=await setup();repo.create(record());const complete=repo.finish(owner,'capture-1',token,'complete',now+1)!;const approved=repo.approve(owner,'capture-1',complete.snapshotHash!,now+2)!;expect(repo.get(owner,'capture-1')).toEqual(approved);
    db.connection.prepare('UPDATE drift_snapshots SET approved_at=? WHERE owner_key=?').run(now+3,owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');
    db.connection.prepare('UPDATE drift_snapshots SET approved_at=? WHERE owner_key=?').run(now+2,owner);db.connection.prepare('UPDATE drift_snapshots SET approval_hash=? WHERE owner_key=?').run('0'.repeat(64),owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');
    db.connection.prepare('UPDATE drift_snapshots SET approval_hash=?,approved_at=? WHERE owner_key=?').run('a'.repeat(9000),'x'.repeat(9000),owner);expect(()=>repo.get(owner,'capture-1')).toThrow('Drift data is corrupt');
  });
});
