import { mkdtemp,rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import type { DurableWorkflow } from '@baitonghub-linux-mcp/domain';
import { SqliteDatabase } from './database.js';
import { incidentFixRecordHash,SqliteIncidentFixRepository,type IncidentFixRecord } from './incident-fix-repository.js';
import { SqliteWorkflowRepository } from './workflow-repository.js';

const roots:string[]=[],databases:SqliteDatabase[]=[];
afterEach(async()=>{for(const db of databases.splice(0)){try{db.close();}catch{/* closed before reopen */}}await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})));});
async function setup():Promise<{file:string;db:SqliteDatabase;fixes:SqliteIncidentFixRepository;workflows:SqliteWorkflowRepository}>{const root=await mkdtemp(path.join(os.tmpdir(),'incident-fix-'));roots.push(root);const file=path.join(root,'records.sqlite'),db=new SqliteDatabase(file);databases.push(db);return{file,db,fixes:new SqliteIncidentFixRepository(db),workflows:new SqliteWorkflowRepository(db)};}
const owner='a'.repeat(64),other='b'.repeat(64),fingerprint='c'.repeat(64),createdAt='2026-10-03T00:00:00.000Z';
function workflow(id='workflow-1',ownerKey=owner,workspaceId='workspace-1',time=createdAt):DurableWorkflow{const contract={taskId:'task-1',workspaceId,dependencies:[],contextReference:{linkHash:'d'.repeat(64)}};return{id,ownerKey,workspaceId,createdAt:time,tasks:[{taskId:'task-1',contractJson:JSON.stringify(contract),dependencies:[],state:'ready',revision:0,checkpoint:null}]};}
function record(id='fix-1',wf=workflow(),document:unknown={schema:1,workspaceId:wf.workspaceId,context:[],contract:JSON.parse(wf.tasks[0]!.contractJson)}):IncidentFixRecord{const input={id,ownerKey:wf.ownerKey,workflowId:wf.id,requestFingerprint:fingerprint,document,createdAt:wf.createdAt};return{...input,documentHash:incidentFixRecordHash(input)!};}

describe('SqliteIncidentFixRepository',()=>{
  it('creates an immutable workflow link and resolves by owner, ID and workflow across reopen',async()=>{const{file,db,fixes}=await setup();const wf=workflow(),r=record('fix-1',wf);expect(fixes.create(r,wf)).toBe(true);expect(fixes.create(r,wf)).toBe(false);const alternate=workflow('workflow-2');expect(fixes.create(record(r.id,alternate),alternate)).toBe(false);expect(fixes.getByWorkflow(owner,alternate.id)).toBeNull();expect(fixes.get(other,r.id)).toBeNull();expect(fixes.getByWorkflow(other,wf.id)).toBeNull();expect(fixes.get(owner,r.id)).toEqual(r);expect(fixes.getByWorkflow(owner,wf.id)).toEqual(r);db.close();const reopened=new SqliteDatabase(file);databases.push(reopened);const again=new SqliteIncidentFixRepository(reopened);expect(again.get(owner,r.id)).toEqual(r);expect(again.getByWorkflow(owner,wf.id)).toEqual(r);});
  it('binds normalized IDs, owner, workspace, workflow time, task contract, task count and canonical hash',async()=>{const{fixes}=await setup();const wf=workflow(),r=record('fix-1',wf);expect(fixes.create({...r,documentHash:'e'.repeat(64)},wf)).toBe(false);expect(fixes.create(record('bad-workspace',wf,{workspaceId:'other'}),wf)).toBe(false);expect(fixes.create(record('bad-time',wf),{...wf,createdAt:'2026-10-03T00:00:01.000Z'})).toBe(false);expect(fixes.create(r,{...wf,tasks:[...wf.tasks,...wf.tasks.map(task=>({...task,taskId:'task-2',contractJson:JSON.stringify({...JSON.parse(task.contractJson),taskId:'task-2'})}))]})).toBe(false);const mismatch=workflow('workflow-contract-mismatch');expect(fixes.create(record('mismatch',mismatch,{schema:1,workspaceId:mismatch.workspaceId,context:[],contract:{...JSON.parse(mismatch.tasks[0]!.contractJson),taskId:'other-task'}}),mismatch)).toBe(false);expect(fixes.getByWorkflow(owner,mismatch.id)).toBeNull();});
  it('rejects noncanonical object graphs and detects tampered or oversized SQL fields',async()=>{const{db,fixes}=await setup();const wf=workflow(),r=record('fix-1',wf),cycleWorkflow=workflow('workflow-cycle');const cycle:Record<string,unknown>={workspaceId:wf.workspaceId};cycle.self=cycle;expect(fixes.create(record('cycle',cycleWorkflow,cycle),cycleWorkflow)).toBe(false);const accessorWorkflow=workflow('workflow-accessor'),accessor=Object.defineProperty({workspaceId:wf.workspaceId},'secret',{enumerable:true,get():string{return'never-read';}});expect(fixes.create(record('accessor',accessorWorkflow,accessor),accessorWorkflow)).toBe(false);expect(fixes.create(r,wf)).toBe(true);
    db.connection.prepare('UPDATE incident_fix_records SET document_hash=? WHERE id=?').run('e'.repeat(64),r.id);expect(()=>fixes.get(owner,r.id)).toThrow('Incident fix data is corrupt');
    const canonical='{"context":[],"contract":{"contextReference":{"linkHash":"'+ 'd'.repeat(64) +'"},"dependencies":[],"taskId":"task-1","workspaceId":"workspace-1"},"schema":1,"workspaceId":"workspace-1"}';
    db.connection.prepare('UPDATE incident_fix_records SET document_hash=?,document_json=? WHERE id=?').run(r.documentHash,'{"workspaceId":"workspace-1","schema":1,"context":[],"contract":{"taskId":"task-1","workspaceId":"workspace-1","dependencies":[],"contextReference":{"linkHash":"'+ 'd'.repeat(64) +'"}}}',r.id);expect(()=>fixes.get(owner,r.id)).toThrow('Incident fix data is corrupt');
    db.connection.prepare('UPDATE incident_fix_records SET document_json=? WHERE id=?').run('x'.repeat(40*1024),r.id);expect(()=>fixes.get(owner,r.id)).toThrow('Incident fix data is corrupt');
    db.connection.prepare('UPDATE incident_fix_records SET document_json=?,request_fingerprint=? WHERE id=?').run(canonical,'x'.repeat(65),r.id);expect(()=>fixes.get(owner,r.id)).toThrow('Incident fix data is corrupt');
    db.connection.prepare('UPDATE incident_fix_records SET request_fingerprint=?,created_at=? WHERE id=?').run(fingerprint,'x'.repeat(25),r.id);expect(()=>fixes.get(owner,r.id)).toThrow('Incident fix data is corrupt');});
  it('rolls back workflow and creation events when the linked record insert fails',async()=>{const{db,fixes,workflows}=await setup();db.connection.exec("CREATE TRIGGER reject_incident_fix BEFORE INSERT ON incident_fix_records BEGIN SELECT RAISE(ABORT,'fixture insert failure'); END;");const wf=workflow(),r=record('trigger-fail',wf);expect(fixes.create(r,wf)).toBe(false);expect(workflows.get(owner,wf.id)).toBeNull();expect(workflows.events(owner,wf.id,0,10)).toEqual([]);expect(fixes.get(owner,r.id)).toBeNull();expect(fixes.getByWorkflow(owner,wf.id)).toBeNull();});
  it('leaves no linked record when workflow quota rejects creation',async()=>{const{db,fixes,workflows}=await setup();for(let i=0;i<32;i++)workflows.create(workflow(`existing-${i}`));const wf=workflow('quota-blocked'),r=record('quota-blocked-fix',wf);expect(fixes.create(r,wf)).toBe(false);expect(workflows.get(owner,wf.id)).toBeNull();expect(fixes.get(owner,r.id)).toBeNull();expect(fixes.getByWorkflow(owner,wf.id)).toBeNull();const rows=db.connection.prepare('SELECT COUNT(*) n FROM incident_fix_records').get() as {n:number|bigint};expect(Number(rows.n)).toBe(0);});
  it('enforces 32 per owner and 256 global linked record quotas',async()=>{const{fixes}=await setup();for(let i=0;i<32;i++){const wf=workflow(`own-${i}`);expect(fixes.create(record(`own-fix-${i}`,wf),wf)).toBe(true);}const over=workflow('own-over');expect(fixes.create(record('own-fix-over',over),over)).toBe(false);
    for(let group=1;group<8;group++)for(let i=0;i<32;i++){const key=group.toString(16).repeat(64),wf=workflow(`global-${group}-${i}`,key);expect(fixes.create(record(`global-fix-${group}-${i}`,wf),wf)).toBe(true);}
    const final=workflow('global-over','e'.repeat(64));expect(fixes.create(record('global-fix-over',final),final)).toBe(false);});
});
