import { mkdtemp, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { SqliteDatabase } from './database.js';
import { SqliteIncidentRepository, type IncidentRecord } from './incident-repository.js';

const roots:string[]=[]; const dbs:SqliteDatabase[]=[];
afterEach(async()=>{for(const db of dbs.splice(0)){try{db.close();}catch{/* Already closed by reopen fixture. */}}await Promise.all(roots.splice(0).map((r)=>rm(r,{recursive:true,force:true})));});
async function setup(): Promise<{ db: SqliteDatabase; file: string; repo: SqliteIncidentRepository }>{const root=await mkdtemp(path.join(os.tmpdir(),'incident-'));roots.push(root);const file=path.join(root,'db.sqlite');const db=new SqliteDatabase(file);dbs.push(db);return {db,file,repo:new SqliteIncidentRepository(db)};}
const owner='a'.repeat(64), other='b'.repeat(64), fingerprint='c'.repeat(64), token='d'.repeat(64), now=1_800_000_000_000;
function record(id='case-1',ownerKey=owner):IncidentRecord{return {id,ownerKey,requestFingerprint:fingerprint,runToken:token,state:'collecting',header:{requested:['health']},createdAt:now,expiresAt:now+60_000,updatedAt:now};}

describe('SqliteIncidentRepository',()=>{
  it('persists and isolates owners, rejects duplicate IDs, and survives restart',async()=>{const {db,file,repo}=await setup();const r=record();expect(repo.create(r)).toBe(true);expect(repo.create({...r,requestFingerprint:'e'.repeat(64)})).toBe(false);expect(repo.get(other,r.id)).toBeNull();expect(repo.get(owner,r.id)).toEqual(r);db.close();const reopened=new SqliteDatabase(file);dbs.push(reopened);expect(new SqliteIncidentRepository(reopened).get(owner,r.id)).toEqual(r);});
  it('fences appends by token, state and deadline; keeps terminal rows immutable',async()=>{const {repo}=await setup();const r=record();expect(repo.create(r)).toBe(true);const e=repo.append(owner,r.id,'e'.repeat(64),{a:1},now);expect(e).toBeNull();const first=repo.append(owner,r.id,token,{z:2,a:1},now);expect(first?.sequence).toBe(1);expect(first?.hash).toMatch(/^[a-f0-9]{64}$/);expect(repo.append(owner,r.id,token,{early:true},now-1)).toBeNull();expect(repo.finish(owner,r.id,token,'partial',now+60_001)).toBe(false);expect(repo.finish(owner,r.id,token,'partial',now+1)).toBe(true);expect(repo.append(owner,r.id,token,{late:true},now+60_001)).toBeNull();expect(repo.finish(owner,r.id,token,'complete',now)).toBe(false);expect(repo.summary(owner,r.id)).toEqual({count:1,bytes:13});});
  it('pages in sequence order and validates every retained payload hash',async()=>{const {repo}=await setup();const r=record();repo.create(r);for(let i=0;i<20;i++)expect(repo.append(owner,r.id,token,{n:i},now)?.sequence).toBe(i+1);expect(repo.listEvidence(owner,r.id,15,4).map(x=>x.sequence)).toEqual([16,17,18,19]);expect(repo.listEvidence(owner,r.id,0,32)).toHaveLength(20);});
  it('enforces row and byte quotas and input bounds',async()=>{const {repo}=await setup();const r=record();expect(repo.create({...r,header:{s:'x'.repeat(8192)}})).toBe(false);expect(repo.create({...r,id:'bad id'})).toBe(false);expect(repo.create(r)).toBe(true);for(let i=0;i<128;i++)expect(repo.append(owner,r.id,token,{i},now)).not.toBeNull();expect(repo.append(owner,r.id,token,{overflow:true},now)).toBeNull();expect(repo.summary(owner,r.id)?.count).toBe(128);});
  it('validates lowercase owner hashes and rejects non-JSON or overly deep values',async()=>{const {repo}=await setup();expect(repo.create(record('case-1','A'.repeat(64)))).toBe(false);expect(repo.create(record('_bad'))).toBe(false);expect(repo.create(record())).toBe(true);expect(repo.append(owner,'case-1',token,{value:undefined},now)).toBeNull();expect(repo.append(owner,'case-1',token,{value:1n},now)).toBeNull();let deep:unknown={};for(let i=0;i<35;i++)deep={nested:deep};expect(repo.append(owner,'case-1',token,deep,now)).toBeNull();});
  it('fails closed when retained evidence exceeds aggregate byte quota',async()=>{const {db,repo}=await setup();repo.create(record());const payload={s:'x'.repeat(4000)};for(let i=0;i<65;i++)expect(repo.append(owner,'case-1',token,payload,now)).not.toBeNull();expect(repo.append(owner,'case-1',token,payload,now)).toBeNull();const json=JSON.stringify(payload);const hash=createHash('sha256').update(json,'utf8').digest('hex');db.connection.prepare('INSERT INTO incident_evidence(owner_key,incident_id,sequence,hash,payload_json) VALUES(?,?,?,?,?)').run(owner,'case-1',66,hash,json);expect(()=>repo.summary(owner,'case-1')).toThrow('Incident data is corrupt');expect(()=>repo.listEvidence(owner,'case-1')).toThrow('Incident data is corrupt');});
  it('enforces owner and global incident quotas',async()=>{const {repo}=await setup();for(let o=0;o<8;o++){const key=o.toString(16).repeat(64);for(let i=0;i<32;i++)expect(repo.create(record(`i-${i}`,key))).toBe(true);}expect(repo.create(record('global-over','f'.repeat(64)))).toBe(false);expect(repo.create(record('owner-over','0'.repeat(64)))).toBe(false);});
  it('bounds SQL projections and fails closed on corrupt headers and evidence',async()=>{const {db,repo}=await setup();const r=record();repo.create(r);repo.append(owner,r.id,token,{safe:true},now);db.connection.prepare('UPDATE incidents SET header_json=? WHERE owner_key=?').run('x'.repeat(9000),owner);expect(()=>repo.get(owner,r.id)).toThrow('Incident data is corrupt');expect(()=>repo.summary(owner,r.id)).toThrow('Incident data is corrupt');db.connection.prepare('UPDATE incidents SET header_json=? WHERE owner_key=?').run('{"requested":["health"]}',owner);db.connection.prepare('UPDATE incident_evidence SET hash=? WHERE owner_key=?').run('0'.repeat(64),owner);expect(()=>repo.listEvidence(owner,r.id)).toThrow('Incident data is corrupt');});
  it('rejects malformed stored numeric and string columns before materialization',async()=>{const {db,repo}=await setup();const r=record();repo.create(r);db.connection.prepare('UPDATE incidents SET expires_at=? WHERE owner_key=?').run('x'.repeat(9000),owner);expect(()=>repo.get(owner,r.id)).toThrow();db.connection.prepare('UPDATE incidents SET expires_at=? WHERE owner_key=?').run(now+60_000,owner);repo.append(owner,r.id,token,{ok:true},now);db.connection.prepare('UPDATE incident_evidence SET sequence=? WHERE owner_key=?').run('9'.repeat(9000),owner);expect(()=>repo.listEvidence(owner,r.id)).toThrow();});
});
